theme: jekyll-theme-dinky
title: Data Science Course IFT6758
description: Data science is a "concept to unify statistics, data analysis, machine learning and their related methods" in order to "understand and analyze actual phenomena" with data
